services:
   jupyter:
      image: jupyter_image
      build:
         context: .
         dockerfile: Dockerfile
      volumes:
         - ./models/:/home/jovyan/models
         - ./data:/home/jovyan/data
         - ./notebooks:/home/jovyan/notebooks
      ports:
         - 8888:8888
           #deploy:
           #   resources:
           #      reservations:
           #         devices:
           #            - driver: nvidia
           #              count: 1
           #              capabilities: [gpu]

   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
      container_name: elastic
      environment:
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
         - "http.host=0.0.0.0"
         - "network.host=0.0.0.0"
         - "transport.host=127.0.0.1"
         - "cluster.name=docker-cluster"
         - "xpack.security.enabled=false"

      ports:
         - "9200:9200"
         - "9300:9300"
      healthcheck:
         test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
         interval: 10s
         timeout: 10s
         retries: 10